pipeline {
    
    agent {
        docker {
            image 'node:14.20'
            args '--file Dockerfile'
        }
    }
    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/tekraveconsulting/quizapp.git', credentialsId: 'gitHubToken'
            }
        }
        //stage('Build') {
        //    steps {
        //        sh 'pip install -r requirements.txt'
        //        sh 'python setup.py sdist bdist_wheel'
        //    }
        //}
        //stage('Deploy to Artifactory') {
        //    steps {
        //        withCredentials([usernamePassword(credentialsId: 'your-artifactory-credentials-id', passwordVariable: 'ARTIFACTORY_PASSWORD', usernameVariable: 'ARTIFACTORY_USERNAME')]) {
        //            sh "curl -u $ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD -X PUT 'http://your-artifactory-url/your-repo/your-package-name-version.tar.gz' -T dist/*"
        //        }
        //    }
        //}
        //stage('Deploy to Docker') {
        //    steps {
        //        withCredentials([usernamePassword(credentialsId: 'your-docker-credentials-id', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
        //            sh 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
        //            sh 'docker build -t your-docker-username/your-image-name:latest .'
        //            sh 'docker push your-docker-username/your-image-name:latest'
        //        }
        //    }
        //}
        //stage('Deploy to Server') {
        //    steps {
        //        withCredentials([sshUserPrivateKey(credentialsId: 'your-ssh-key-id', keyFileVariable: 'SSH_KEY_FILE', usernameVariable: 'SSH_USER')]) {
        //            sh "ansible-playbook -i 'your-server-ip,' deploy.yml -u $SSH_USER --private-key=$SSH_KEY_FILE"
        //        }
        //    }
        //}
    }
}
